# NumPy

In [2]:
import numpy as np

#Creamos un np array de rango 1,
un_array=np.array([7,77,777])
print(type(un_array))

<class 'numpy.ndarray'>


In [5]:
#Imprimimos la forma (shape) de array
print(type(un_array.shape))

print(un_array.shape)

print(un_array)

<class 'tuple'>
(3,)
[  7  77 777]


In [6]:
#Acceder a las varaibles

print(un_array[0])
print(un_array[1])
print(un_array[2])

7
77
777


# Array Multidimensional

In [7]:
multi =np.array([[12,2,32],[53,43,76],[52,79,75]])
print("La forma de este array es: ",multi.shape)

La forma de este array es:  (3, 3)


In [14]:
print(multi[2,0])
print("Para imprimir todo es ")
print(multi)

52
Para imprimir todo es 
[[12  2 32]
 [53 43 76]
 [52 79 75]]


$ I^{n \times n} =
\left( \begin{array}{cccc}
     11 & 12 & 13 \\
     22 & 23 & 24 \\
     33 & 34 & 35 \\
\end{array} \right) $

# Distintas Maneras de cear nd arrays


In [32]:
#Crear array lleno de ceros
ej1=np.zeros([1080,1920,3])
print(ej1)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [29]:
#Creamos un array lleno de un valor determinado(floats por ejemplo)
ej2=np.full((2,2), 9.1)

print(ej2)

[[9.1 9.1]
 [9.1 9.1]]


In [30]:
#Creando un array 2*2 condiagonal en "unos" y el resto ceros
ej3=np.eye(7,7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [37]:
#Creando un array de "unos"
ej4 = np.ones((3,3))

print(ej4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
 #Creamos un aray de flotantes aleatorios entre 0 y 1

ej5 = np.random.random((5,5))

print(ej5)

[[0.7278376  0.00813821 0.58724568 0.67568355 0.30322274]
 [0.38355548 0.94443998 0.86579684 0.03548504 0.9316421 ]
 [0.12561779 0.03081162 0.3009675  0.00927428 0.50276428]
 [0.0861594  0.74877724 0.39692929 0.32302178 0.41675586]
 [0.28039218 0.6412823  0.67602986 0.62765001 0.39704177]]


# Array de Indices

A veces es util,preparar una serie de indices en un array,para luego utilizarlos para operar sobre otro.

In [46]:
#Creamos un nuevo array

array_a = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])

print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [40]:
#Creamos 2 arrays con numeros enteros que usaremoos como indices

cols=np.array([0,1,2,0])
rows=np.arange(4)
print("Elegimos estos indices para filas -> ",rows)
print("Elegimos estos indices para columnas -> ",cols)

Elegimos estos indices para filas ->  [0 1 2 3]
Elegimos estos indices para columnas ->  [0 1 2 0]


In [41]:
#Imprimimos los inices tomando uno de cada array, de a pares,
for row,col in zip(rows,cols):
    print("(",row,",",col,")")

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [42]:
#Entonces ahora para seleccionar un elemento de cada fila, hacemos de esta manera

print("Los valores contenidos en los indices son: ",array_a[rows,cols])

Los valores contenidos en los indices son:  [11 22 33 41]


In [47]:
#Vamos a operar con los valores seleccionados
print(array_a)
array_a[rows,cols] +=1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


# Indexado Boolena

Indexado booleano para cambiar elementos

In [48]:
#Creamos un array de 3x2

array_b = np.array([[11,12],[21,22],[31,32]])
print(array_b)
print("----------------")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
----------------
(3, 2)


In [49]:
#Crear un filtro
filtro =(array_b>15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [50]:
#Aplicamos el filtro a nuestro array
filtrado = array_b[filtro]

print(filtrado)

[21 22 31 32]


In [51]:
#No es necesario crear el filtro

print(array_b[(array_b %2==0)])

[12 22 32]


In [53]:
array_b[array_b%2==0]+=1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


# Rebanando arrays (Slice)

In [59]:
un_array = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46]]) 

print(un_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


In [60]:
#Creamos un slice de 2x2 a partir de "un_array"

un_slice=un_array[:2,1:3]
print(un_slice)

[[12 13]
 [22 23]]


In [61]:
print("Slice: ",un_slice[0,0])

Slice:  12


In [62]:
un_slice[0,0] += 100
print(un_slice)

[[112  13]
 [ 22  23]]


In [63]:
print(un_array)

[[ 11 112  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  44  45  46]]


### *Muy Importante*

y si necesitaramos tener un nuevo array a partir de un slice?

In [64]:
nuevo_array= np.array(un_slice)
print(nuevo_array)

[[112  13]
 [ 22  23]]


In [65]:
#Puedo seleccionar una sola fila, entonces el slice sera unidimensional.

row_rankl= un_array[1,:]
print(row_rankl,row_rankl.shape)

[21 22 23 24 25 26] (6,)


# Tipos de datos de los array numpy

In [66]:
ej1=np.array([11,12])
print(ej1.dtype)

int32


In [67]:
ej2=np.array([11.0,12.0])
print(ej2.dtype)

float64


In [68]:
ej3=np.array([11,21], dtype=np.float64)
print(ej3.dtype)

float64


In [71]:
#Se truncan los datos
ej4=np.array([11.4,21.8], dtype=np.int64)
print(ej4.dtype)
print()
print(ej4)

int64

[11 21]


# Operaciones Aritmeticas

In [72]:
x=np.array([[111,112],[121,122]], dtype=np.int)
y=np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [73]:
#Restar
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [74]:
#Multiplicar
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [75]:
#Division
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [76]:
#Raiz Cuadrada
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


 # Operaciones Estadisticas Basicas 

In [86]:
arr = 10 *np.random.randn(2,5)
print(arr)

[[ 0.35129691  4.37476266  7.49393777  1.84615469  2.64596486]
 [-4.38722421  2.32112755  6.88966145 -7.3993156  22.09523393]]


In [87]:
#Calcular la media (promedio) de un array

print(arr.mean())

3.6231600002406266


In [88]:
#Calcular promedio, fila por fila
# eje 0 = columnas
#eje 1 = filas
print(arr.mean(axis=1))

[3.34242338 3.90389662]


In [89]:
#Calcular promedio, columna por columna
# eje 0 = columnas
#eje 1 = filas
print(arr.mean(axis=0))

[-2.01796365  3.3479451   7.19179961 -2.77658045 12.3705994 ]


In [91]:
#Creamos un array de 10 elementos aleatorios
desordenado = np.random.randn(10)
print(desordenado)

[ 1.51225716  0.30108115  0.43432134  0.06041984 -1.63108092  0.55540579
  0.27792469 -0.07951621 -0.84374408 -0.93444614]


In [92]:
#Creamos una copia 
ordenado = np.array(desordenado)

#lo ordenamos
ordenado.sort()
print(ordenado)

[-1.63108092 -0.93444614 -0.84374408 -0.07951621  0.06041984  0.27792469
  0.30108115  0.43432134  0.55540579  1.51225716]


In [95]:
#buscando elementos unicos 
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [96]:
#Operaciones de conjunto

s1 = np.array(['escritorio','silla','mesa'])
s2 = np.array(['escritorio','silla','lampara'])
print(s1)
print(s2)

['escritorio' 'silla' 'mesa']
['escritorio' 'silla' 'lampara']


In [97]:
#Interseccion
print(np.intersect1d(s1,s2))

['escritorio' 'silla']


In [98]:
#Union en id
print(np.union1d(s1,s2))

['escritorio' 'lampara' 'mesa' 'silla']


In [99]:
#elementos de s1 que no estan en s2
print(np.setdiff1d(s1,s2))

['mesa']


In [100]:
#que elementos de s1 estan en s2
print(np.in1d(s1,s2))

[ True  True False]


# Algunas Operaciones Frecuentes

In [101]:
 #sumamos todos los elementos de un array
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [102]:
#Sumamos solo una columna
print(np.sum(ex1, axis=0))
#Sumamos solo una fila
print(np.sum(ex1, axis=1))

[32 34]
[23 43]


### Reformateando un array

In [103]:
arr = np.arange(20)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(20,)

In [105]:
#Cambiamos su forma
reshped_arr = arr.reshape(4,5)
print(reshped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [106]:
#Trasnponer o transposicionar un array
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex1.T

[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [109]:
#Where
mat = np.random.rand(4,4)
mat

array([[0.30225217, 0.30045039, 0.72899872, 0.44444996],
       [0.64053412, 0.5546215 , 0.80992333, 0.27183665],
       [0.25756656, 0.76409762, 0.33131636, 0.46562142],
       [0.06502058, 0.13444499, 0.80082651, 0.48080715]])

In [111]:
np.where(mat>0.5,1000,-1)

array([[  -1,   -1, 1000,   -1],
       [1000, 1000, 1000,   -1],
       [  -1, 1000,   -1,   -1],
       [  -1,   -1, 1000,   -1]])

In [112]:
arr_bools= np.array([0,0,0,0,0,True])
arr_bools.any()

True

In [115]:
 arr_bools= np.array([1,1,True])
arr_bools.all()

True

### Uniendo data sets

In [116]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[16 27]
 [47 35]]

[[31 13]
 [ 7 19]]


In [118]:
#Unimos "ampliando" verticalmente
np.vstack((K,M))

array([[16, 27],
       [47, 35],
       [31, 13],
       [ 7, 19]])

In [119]:
#Unimos "ampliando" horizontalmente
np.hstack((K,M))

array([[16, 27, 31, 13],
       [47, 35,  7, 19]])

In [120]:
#Podemos unir concatenando
np.concatenate((K,M), axis=0)

array([[16, 27],
       [47, 35],
       [31, 13],
       [ 7, 19]])

In [121]:
np.concatenate((K,M), axis=1)

array([[16, 27, 31, 13],
       [47, 35,  7, 19]])

# Propagacion

In [122]:
base = np.zeros((4,4))

In [123]:
#Creamos un array unidimensional
row = np.array([1,0,2,7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [124]:
y = base+row
print(y)

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [127]:
col = np.array([[0,1,2,3]])
print(col)

[[0 1 2 3]]


In [128]:
col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [129]:
y = base+col
print(y)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [130]:
col=np.array([[0,1,2]])
col = col.T
print(col)

[[0]
 [1]
 [2]]


In [131]:
y = base+col
print(y)

ValueError: operands could not be broadcast together with shapes (4,4) (3,1) 

In [132]:
arr_x=np.array([4])
print(arr_x)
print("___________________")
print(base+arr_x)

[4]
___________________
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


# Prueba de Velocidad

In [133]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits=1000

nd_array = arange(size)
print("Tipo de dato -> ",type(nd_array))
print("Forma -> ",nd_array.shape)

Tipo de dato ->  <class 'numpy.ndarray'>
Forma ->  (1000000,)


In [134]:
#con la funcion timer podemos medir, el tiempo que lleva realizar una operacion o funcion

timer_numpy=Timer("nd_array.sum()","from __main__ import nd_array")
print("Time que toma Numpy nd_array: %f segundos" % (timer_numpy.timeit(timeits)))

Time que toma Numpy nd_array: 0.816090 segundos


In [135]:
a_list = list(range(size))
print(type(a_list))
print("Forma -> ", len(a_list))

<class 'list'>
Forma ->  1000000


In [136]:
timer_list = Timer("sum(a_list)","from __main__ import a_list")
print("Time que toma la lista: %f segundos" % (timer_list.timeit(timeits)))

Time que toma la lista: 52.623954 segundos


## Grabar array a disco / recuperar array de disco

In [137]:
x=np.array([23.23,24.24])

In [138]:
np.save('array_importante',x)

In [139]:
recuperado = np.load('array_importante.npy')
print("El array recuperado es: ",recuperado)

El array recuperado es:  [23.23 24.24]
